name: upper-build

# Github Action Trigger on push
on:
  push:
    paths: 
        - ".github/workflows/upper-build.yml"
        - "upper/**"
  workflow_dispatch: # manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - run: go version
          - uses: actions/setup-go@v5
            with:
                go-version: '1.22'
          - run: go version
            